# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('backend', models.CharField(choices=[('helpful.easy_email:mail', 'Easy e-mail'), ('helpful.sms:send_sms', 'SMS.RU')], max_length=128, verbose_name='Backend')),
                ('on_create', models.BooleanField(default=True, verbose_name='On create')),
                ('on_change', models.BooleanField(default=False, verbose_name='On change')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ManyToManyField(to='contenttypes.ContentType', verbose_name='Models')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Notify',
                'verbose_name_plural': 'Notifies',
            },
        ),
        migrations.CreateModel(
            name='NotifyProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('key', models.SlugField(max_length=128, verbose_name='Key')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Value')),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='notify.Notify', verbose_name='Notify')),
            ],
            options={
                'ordering': ['notify', 'name'],
                'verbose_name': 'Notify property',
                'verbose_name_plural': 'Notify properties',
            },
        ),
    ]
