# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='backend',
            field=models.CharField(choices=[('apps.notify.tests.console', 'Console'), ('helpful.easy_email.mail', 'Easy e-mail'), ('helpful.sms.send_sms', 'SMS.RU')], max_length=128, verbose_name='Backend'),
        ),
    ]
